server:
  port: 10001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/springboot?
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis: # 配置redis
      host: 192.168.47.129
      port: 6379
mybatis:
  type-aliases-package: com.atguigu.pojo   #别名包
